 #github FUNDING yml

content: my crypto ruzyysmartt

https://github.com/https-github-com-ruzyysmartt/MyCrypto-ruzyysmartt/edit/master/.github/FUNDING.yml
custom:
https://donate.unlock-protocol.com/?r=mycryptohq/mycrypto
